version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    # Limit the number of open pull requests for npm updates
    open-pull-requests-limit: 5
    # Security updates only for production dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Assign reviewers for dependency updates
    reviewers:
      - "yeshelpnetwork"
    # Set commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group updates by dependency type
    groups:
      next-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      mui-ecosystem:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
    # Ignore specific packages that require manual updates
    ignore:
      # Ignore patch updates for stable packages
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Security vulnerability alerts
    security-advisories:
      enabled: true

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"
