version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    # Limit the number of open pull requests for npm updates
    open-pull-requests-limit: 3
    # Allow security updates and minor/patch updates only
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      # Always allow security updates regardless of semver
      - dependency-type: "all"
        update-types: ["version-update:security"]
    # Assign reviewers for dependency updates
    reviewers:
      - "yeshelpnetwork"
    # Set commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group updates by dependency type to reduce PR noise
    groups:
      next-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
        update-types:
          - "patch"
          - "minor"
          - "security"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "patch"
          - "minor"
          - "security"
      mui-ecosystem:
        patterns:
          - "@mui/*"
          - "@emotion/*"
        update-types:
          - "patch"
          - "minor"
          - "security"
      dev-tools:
        dependency-type: "development"
        patterns:
          - "eslint*"
          - "@types/*"
          - "typescript"
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "patch"
          - "minor"
          - "security"
    # Ignore major version updates for critical dependencies
    ignore:
      # Ignore major React updates - require manual review
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Ignore major Next.js updates - require manual review
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      # Ignore major MUI updates - often have breaking changes
      - dependency-name: "@mui/*"
        update-types: ["version-update:semver-major"]
      # Ignore major TypeScript updates - can break builds
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      # Ignore major ESLint updates - rule changes can break CI
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"